version: "3"

services:

  bebop-bot:
    container_name: bebop-bot
    image: bebop-bot:1.0.2
    build: .
    environment:
      - bot_username=<bot_username>
      - bot_token=<bot_token>
      - vk_user_id=<vk_user_id>
      - vk_token=<vk_token>
      - vk_audio_groups_ids=<vk_audio_groups_ids>
      - vk_photo_groups_ids=<vk_photo_groups_ids>
      #-wall_post_groups_scope=<vk_owned_groups_ids>
      #- bot_threads=<count>
      #- bot_proxy_type=<HTTP|SOCKS4|SOCKS5>
      #- bot_proxy_host=<host>
      #- bot_proxy_port=<port>

